name: compress_images_flutter
description: Plugin flutter for compress images using your path in memory device, functional in Ios and Android Platforms.
version: 0.0.3+8
homepage: https://github.com/renanzdm/compress_images_flutter
environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  plugin:
    platforms:
      android:
        package: com.example.compress_images_flutter
        pluginClass: CompressImagesFlutterPlugin
      ios:
        pluginClass: CompressImagesFlutterPlugin


